substitutions:
  _REGION: asia-northeast1
  _SERVICE: minishop
  _AR_REPOSITORY: cloud-run-source-deploy
  _IMAGE_NAME: minishop
  _SERVICE_ACCOUNT_NAME: minishop-runner
  _TAG: latest

timeout: 1200s

steps:
  - id: Build image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - .

  - id: Push image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}

  - id: Deploy to Cloud Run
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT_NAME}@$PROJECT_ID.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --memory=1Gi
      - --cpu=1
      - --min-instances=0
      - --max-instances=2
      - --set-env-vars=SPRING_PROFILES_ACTIVE=prod
      - --set-secrets=DB_URL=DB_URL:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,REDIS_URL=REDIS_URL:latest,JWT_SECRET=JWT_SECRET:latest,TOSS_SECRET_KEY=TOSS_SECRET_KEY:latest

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:${_TAG}
